export const popertyData = [
  {
    image: require("./../../../assets/images/home1.jpg"),
    title: "Rejuvenation Spire ",
    tag: "Appartment",
    address: "209, Parvati Indl. Estate, Sun Mill Compound, Lower Parel",
    beds: "2,4",
    price: "3.5",
    possession: "10 Aug",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home2.jpg"),
    title: "Orchestra Spire",
    tag: "Flat",
    address: "1st Floor, 13, Prabhadevi Indl Estate, Prabhadevi",
    beds: "4,5",
    price: "2.4",
    possession: "13 Aug",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home3.jpg"),
    title: "Homage Spire",
    tag: "Tenament",
    address: "2susheelard, 1stcrs,doddamavalli,b-4, Dodda Mavalli",
    beds: "3,4",
    price: "6.8",
    possession: "12 Jan",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home4.jpg"),
    title: "Serenity Mast",
    tag: "Appartment",
    address:
      "Shop No.2, Vasant Smruti, Thakur Complex, 90 Feet Road, Kandivali (east)",
    beds: "2,4",
    price: "5.00",
    possession: "10 Sep",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home5.jpg"),
    title: "Judgment Spire",
    tag: "Flat",
    address: " 2-4-945, Kachiguda",
    beds: "1,2",
    price: "3.00",
    possession: "10 Feb",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home6.jpg"),
    title: "Grand Hill Lookout",
    tag: "Tenament",
    address: "53/7,iticlny,32ndmn,7thcrs,j.p.ng, Jp Nagar",
    beds: "4",
    price: "10.00",
    possession: "21 Jan",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home7.jpg"),
    title: "Terror Cliff Tower",
    tag: "Flat",
    address: " 1, Palekar Chambers, 12,1st Marine Street, Dhobi Talao",
    beds: "5",
    price: "3.6",
    possession: "15 June",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home1.jpg"),
    title: "Smoke Morass Tower",
    tag: "Appartment",
    address: "Pos;, 24 Off. M. V. Road, Nr Asent Center,",
    beds: "2",
    price: "6.00",
    possession: "10 Nov",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home2.jpg"),
    title: "Barbarian Mire Tower",
    tag: "Flat",
    address: " Govind Niwas, Dadabhai Road, Vile Parle(w)",
    beds: "3",
    price: "7.00",
    possession: "10 Dec",
    measure: "2000 srft - 3000sqft",
  },
  {
    image: require("./../../../assets/images/home3.jpg"),
    title: "White Grotto Pillar",
    tag: "Tenament",
    address: "  18d, Park Street, Middleton Row",
    beds: "2,3",
    price: "6.00",
    possession: "31 Dec",
    measure: "2000 srft - 3000sqft",
  },
];
